
- name: reboot server
  shell: /sbin/reboot

- name: wait for the server to go down 
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30

